name: final_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  curved_navigation_bar:
  google_fonts: any
  date_format: any
  cached_network_image: any
  charts_flutter: any
  fl_chart: any
  jiffy: any
  flutter:
    sdk: flutter
  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/account.json
    - assets/data/heartrate.json
    - assets/data/sleep.json
    - assets/data/activity.json
